import { z } from 'zod/v4';

const LinkSchema = z.object({
  id: z.string(),
  parent: z.string().nullable().optional(),
  row_level: z.coerce.number(),
  permission_name: z.string().nullable().optional(),
  position: z.coerce.number(),
  name_es: z.coerce.string(),
  link: z.coerce.string(),
  icon: z.coerce.string(),
  comment_es: z.coerce.string(),
});

// Generate from database
// Run query => 
// select
// json_agg(
//     json_build_object(
//         'id', a.id,
//         'parent', a.parent,
//         'row_level', a.row_level,
//         'permission_name', a.permission_name,
//         'position', a.position,
//         'name_es', a.name_es,
//         'link', a.link,
//         'icon', a.icon,
//         'comment_es', a.comment_es
//     )
//     ORDER BY id ASC
// )results
// from sys_links a
// Save as json
export const SystemLinks = LinkSchema.array().parse(
  [
    {
        "id": "01",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 1,
        "name_es": "Sistema",
        "link": "/security",
        "icon": "i-lucide-cog",
        "comment_es": "Administración de usuarios, perfiles, compañías.."
    },
    {
        "id": "0101",
        "parent": "01",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Usuarios",
        "link": "/security/users",
        "icon": "i-lucide-users-round",
        "comment_es": "Ver, crear, editar usuarios"
    },
    {
        "id": "010100",
        "parent": "0101",
        "row_level": 2,
        "permission_name": "USERS_READ",
        "position": 0,
        "name_es": "Usuario",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "010101",
        "parent": "0101",
        "row_level": 2,
        "permission_name": "USERS_CREATE",
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "010102",
        "parent": "0101",
        "row_level": 2,
        "permission_name": "USERS_EDIT",
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "010103",
        "parent": "0101",
        "row_level": 2,
        "permission_name": "USERS_EXPORT",
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0102",
        "parent": "01",
        "row_level": 1,
        "permission_name": null,
        "position": 2,
        "name_es": "Perfiles de Seguridad",
        "link": "/security/profiles",
        "icon": "i-lucide-circle-user",
        "comment_es": "Ver, crear, editar roles"
    },
    {
        "id": "010200",
        "parent": "0102",
        "row_level": 2,
        "permission_name": "ROLES_READ",
        "position": 0,
        "name_es": "Perfil",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "010201",
        "parent": "0102",
        "row_level": 2,
        "permission_name": "ROLES_CREATE",
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "010202",
        "parent": "0102",
        "row_level": 2,
        "permission_name": "ROLES_EDIT",
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "010203",
        "parent": "0102",
        "row_level": 2,
        "permission_name": "ROLES_EXPORT",
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0103",
        "parent": "01",
        "row_level": 1,
        "permission_name": null,
        "position": 3,
        "name_es": "Organizaciones / Compañías",
        "link": "/security/companies",
        "icon": "i-lucide-building-2",
        "comment_es": "Ver, crear, editar compañías"
    },
    {
        "id": "010300",
        "parent": "0103",
        "row_level": 2,
        "permission_name": "COMPANIES_READ",
        "position": 0,
        "name_es": "Organización",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "010301",
        "parent": "0103",
        "row_level": 2,
        "permission_name": "COMPANIES_CREATE",
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "010302",
        "parent": "0103",
        "row_level": 2,
        "permission_name": "COMPANIES_EDIT",
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "010303",
        "parent": "0103",
        "row_level": 2,
        "permission_name": "COMPANIES_EXPORT",
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "02",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 2,
        "name_es": "Catálogos",
        "link": "/company?/system",
        "icon": "i-lucide-database",
        "comment_es": "Administración de proveedores, productos, servicios, bodegas.."
    },
    {
        "id": "0201",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Clientes y Proveedores",
        "link": "/company?/system/partners",
        "icon": "i-lucide-handshake",
        "comment_es": "Ver, crear, editar clientes y proveedores"
    },
    {
        "id": "020100",
        "parent": "0201",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020101",
        "parent": "0201",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020102",
        "parent": "0201",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020103",
        "parent": "0201",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0202",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 2,
        "name_es": "Productos y Servicios",
        "link": "/company?/system/items",
        "icon": "i-lucide-briefcase-business",
        "comment_es": "Ver, crear, editar productos y servicios"
    },
    {
        "id": "020200",
        "parent": "0202",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020201",
        "parent": "0202",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020202",
        "parent": "0202",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020203",
        "parent": "0202",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0203",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 3,
        "name_es": "Bodegas",
        "link": "/company?/system/warehouses",
        "icon": "i-lucide-warehouse",
        "comment_es": "Ver, crear, editar bodegas"
    },
    {
        "id": "020300",
        "parent": "0203",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020301",
        "parent": "0203",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020302",
        "parent": "0203",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020303",
        "parent": "0203",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0204",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 4,
        "name_es": "Medidas",
        "link": "/company?/system/units",
        "icon": "i-lucide-ruler-dimension-line",
        "comment_es": "Ver, crear, editar unidades de medida"
    },
    {
        "id": "020400",
        "parent": "0204",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020401",
        "parent": "0204",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020402",
        "parent": "0204",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020403",
        "parent": "0204",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0205",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 5,
        "name_es": "Marcas (Productos)",
        "link": "/company?/system/brands",
        "icon": "i-lucide-group",
        "comment_es": "Ver, crear, editar marcas"
    },
    {
        "id": "020500",
        "parent": "0205",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020501",
        "parent": "0205",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020502",
        "parent": "0205",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020503",
        "parent": "0205",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "0206",
        "parent": "02",
        "row_level": 1,
        "permission_name": null,
        "position": 6,
        "name_es": "Clasificación (Productos)",
        "link": "/company?/system/item_types",
        "icon": "i-lucide-list-tree",
        "comment_es": "Ver, crear, editar tipos de Productos y Servicios"
    },
    {
        "id": "020600",
        "parent": "0206",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "020601",
        "parent": "0206",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "020602",
        "parent": "0206",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "020603",
        "parent": "0206",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "03",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 3,
        "name_es": "Finanzas",
        "link": "/company?/finances",
        "icon": "i-lucide-circle-dollar-sign",
        "comment_es": "Administración contable"
    },
    {
        "id": "0301",
        "parent": "03",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/finances/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "030100",
        "parent": "0301",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "04",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 4,
        "name_es": "Bancos",
        "link": "/company?/banks",
        "icon": "i-lucide-banknote",
        "comment_es": "Administración de bancos"
    },
    {
        "id": "0401",
        "parent": "04",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/banks/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "040100",
        "parent": "0401",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "05",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 5,
        "name_es": "Ventas",
        "link": "/company?/sales",
        "icon": "i-lucide-store",
        "comment_es": "Administración de cuentas x cobrar"
    },
    {
        "id": "0501",
        "parent": "05",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/sales/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "050100",
        "parent": "0501",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "06",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 6,
        "name_es": "Compras",
        "link": "/company?/purchase",
        "icon": "i-lucide-shopping-cart",
        "comment_es": "Administración de cuentas x pagar"
    },
    {
        "id": "0601",
        "parent": "06",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/purchase/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "060100",
        "parent": "0601",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "07",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 7,
        "name_es": "Inventario",
        "link": "/company?/inventory",
        "icon": "i-lucide-warehouse",
        "comment_es": "Administración de inventarios"
    },
    {
        "id": "0701",
        "parent": "07",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/inventory/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "070100",
        "parent": "0701",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "08",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 8,
        "name_es": "Empleados",
        "link": "/company?/rrhh",
        "icon": "i-lucide-id-card-lanyard",
        "comment_es": "Administración de empleados"
    },
    {
        "id": "0801",
        "parent": "08",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/rrhh/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "080100",
        "parent": "0801",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "09",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 9,
        "name_es": "Producción",
        "link": "/company?/mfg",
        "icon": "i-lucide-wrench",
        "comment_es": "Administración de insumos, lotes"
    },
    {
        "id": "0901",
        "parent": "09",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Pending..",
        "link": "/company?/mfg/pending",
        "icon": "i-lucide-loader",
        "comment_es": ""
    },
    {
        "id": "090100",
        "parent": "0901",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "10",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 10,
        "name_es": "Obras y Proyectos",
        "link": "/company?/projects",
        "icon": "i-lucide-pencil-ruler",
        "comment_es": "Administración de obras y proyectos"
    },
    {
        "id": "1001",
        "parent": "10",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Presupuestos",
        "link": "/company?/projects/pending",
        "icon": "i-lucide-calculator",
        "comment_es": "Administrar Presupuestos"
    },
    {
        "id": "100100",
        "parent": "1001",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "100101",
        "parent": "1001",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "100102",
        "parent": "1001",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "100103",
        "parent": "1001",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "11",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 11,
        "name_es": "ENS",
        "link": "/ens",
        "icon": "i-lucide-church",
        "comment_es": "Equipos de Nuestra Señora"
    },
    {
        "id": "1101",
        "parent": "11",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Equipistas",
        "link": "/ens/equipistas",
        "icon": "i-heroicons-users",
        "comment_es": "Ver, crear, editar equipistas"
    },
    {
        "id": "110100",
        "parent": "1101",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "110101",
        "parent": "1101",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "110102",
        "parent": "1101",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "110103",
        "parent": "1101",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1102",
        "parent": "11",
        "row_level": 1,
        "permission_name": null,
        "position": 2,
        "name_es": "Equipos",
        "link": "/ens/equipos",
        "icon": "i-heroicons-user-group",
        "comment_es": "Ver, crear, editar equipos"
    },
    {
        "id": "110200",
        "parent": "1102",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "110201",
        "parent": "1102",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "110202",
        "parent": "1102",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "110203",
        "parent": "1102",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1103",
        "parent": "11",
        "row_level": 1,
        "permission_name": null,
        "position": 3,
        "name_es": "Servicios",
        "link": "/ens/servicios",
        "icon": "i-heroicons-wrench-screwdriver",
        "comment_es": "Ver, crear, editar equipos"
    },
    {
        "id": "110300",
        "parent": "1103",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "110301",
        "parent": "1103",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "110302",
        "parent": "1103",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "110303",
        "parent": "1103",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1104",
        "parent": "11",
        "row_level": 1,
        "permission_name": null,
        "position": 4,
        "name_es": "Libros",
        "link": "/ens/libros",
        "icon": "i-heroicons-book-open",
        "comment_es": "Ver, crear, editar libros"
    },
    {
        "id": "110400",
        "parent": "1104",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Ver",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "110401",
        "parent": "1104",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "110402",
        "parent": "1104",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "110403",
        "parent": "1104",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "12",
        "parent": null,
        "row_level": 0,
        "permission_name": null,
        "position": 12,
        "name_es": "Bitácora Digital",
        "link": "/company?/bitacora",
        "icon": "i-lucide-shield-check",
        "comment_es": "Plataforma de Control y Monitoreo"
    },
    {
        "id": "1201",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 1,
        "name_es": "Puntos de Control",
        "link": "/company?/bitacora/places",
        "icon": "i-lucide-land-plot",
        "comment_es": "Ver, crear, editar Puntos de Control y Monitoreo"
    },
    {
        "id": "120100",
        "parent": "1201",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Punto de Control",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120101",
        "parent": "1201",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120102",
        "parent": "1201",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120103",
        "parent": "1201",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1202",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 2,
        "name_es": "Vehículos",
        "link": "/company?/bitacora/cars",
        "icon": "i-lucide-car",
        "comment_es": "Ver, crear, editar Vehículos"
    },
    {
        "id": "120200",
        "parent": "1202",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Vehículo",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120201",
        "parent": "1202",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120202",
        "parent": "1202",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120203",
        "parent": "1202",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "1203",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 3,
        "name_es": "Motivos de Visita",
        "link": "/company?/bitacora/reasons",
        "icon": "i-lucide-list-check",
        "comment_es": "Ver, crear, editar Motivos de Visita"
    },
    {
        "id": "120300",
        "parent": "1203",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Motivo",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120301",
        "parent": "1203",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120302",
        "parent": "1203",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120303",
        "parent": "1203",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1204",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 4,
        "name_es": "Registrar Bitácora",
        "link": "/company?/bitacora/placeId?/events",
        "icon": "i-lucide-notebook-pen",
        "comment_es": "Registrar eventos"
    },
    {
        "id": "120400",
        "parent": "1204",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Evento",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120401",
        "parent": "1204",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120402",
        "parent": "1204",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120403",
        "parent": "1204",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1205",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 5,
        "name_es": "Registrar Visita",
        "link": "/company?/bitacora/placeId?/visits",
        "icon": "i-lucide-door-open",
        "comment_es": "Registrar visitas"
    },
    {
        "id": "120500",
        "parent": "1205",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Visita",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120501",
        "parent": "1205",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120502",
        "parent": "1205",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120503",
        "parent": "1205",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1206",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 3,
        "name_es": "Motivos de Viaje",
        "link": "/company?/bitacora/ridesReasons",
        "icon": "i-lucide-list-check",
        "comment_es": "Ver, crear, editar Motivos de Viaje"
    },
    {
        "id": "120600",
        "parent": "1206",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Viaje",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120601",
        "parent": "1206",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120602",
        "parent": "1206",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120603",
        "parent": "1206",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1207",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 6,
        "name_es": "Registrar Viaje",
        "link": "/company?/bitacora/placeId?/rides",
        "icon": "i-lucide-car",
        "comment_es": "Registrar viajes"
    },
    {
        "id": "120700",
        "parent": "1207",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Viaje",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "120701",
        "parent": "1207",
        "row_level": 2,
        "permission_name": null,
        "position": 1,
        "name_es": "Crear",
        "link": "",
        "icon": "i-lucide-circle-plus",
        "comment_es": "Permitir Crear"
    },
    {
        "id": "120702",
        "parent": "1207",
        "row_level": 2,
        "permission_name": null,
        "position": 2,
        "name_es": "Editar",
        "link": "",
        "icon": "i-lucide-pencil",
        "comment_es": "Permitir Editar"
    },
    {
        "id": "120703",
        "parent": "1207",
        "row_level": 2,
        "permission_name": null,
        "position": 3,
        "name_es": "Exportar",
        "link": "",
        "icon": "i-lucide-file-down",
        "comment_es": "Permitir Exportar"
    },
    {
        "id": "1296",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 96,
        "name_es": "Reporte de Visitas",
        "link": "/company?/bitacora/placeId?/visits-report",
        "icon": "i-lucide-file-spreadsheet",
        "comment_es": "Reporte de Visitas"
    },
    {
        "id": "129600",
        "parent": "1296",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Visitas",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "1297",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 97,
        "name_es": "Reporte de Bitácoras",
        "link": "/company?/bitacora/placeId?/events-report",
        "icon": "i-lucide-file-spreadsheet",
        "comment_es": "Reporte de Bitácoras"
    },
    {
        "id": "129700",
        "parent": "1297",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Eventos",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "1298",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 98,
        "name_es": "Reporte de Viajes",
        "link": "/company?/bitacora/placeId?/rides-report",
        "icon": "i-lucide-file-spreadsheet",
        "comment_es": "Reporte de Viajes"
    },
    {
        "id": "129800",
        "parent": "1298",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Viajes",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    },
    {
        "id": "1299",
        "parent": "12",
        "row_level": 1,
        "permission_name": null,
        "position": 99,
        "name_es": "Dashboard",
        "link": "/company?/bitacora/placeId?/dashboard",
        "icon": "i-lucide-gauge",
        "comment_es": "Dashboard"
    },
    {
        "id": "129900",
        "parent": "1299",
        "row_level": 2,
        "permission_name": null,
        "position": 0,
        "name_es": "Dashboard",
        "link": "",
        "icon": "i-lucide-folder-open",
        "comment_es": "Permitir Ver"
    }
  ]
);
export const PermissionsList = SystemLinks.filter(p => p.permission_name).map(p => { return { [p.permission_name!]: p.id }});

export const permissionNames = SystemLinks
    .filter(item => item.permission_name !== null)
    .map(item => item.permission_name) as string[];
// export const permissionNamesEnum = permissionNames as const;
// const DictionarySchema = z.record(z.string(), z.number());
// export const permissionEnum = z.enum(permissionNames as [string, ...string[]]);

// FROM [dbo].[sys_links]
// export enum PermissionsList {
//   USERS_READ = '010100',
//   USERS_CREATE = '010101',
//   USERS_EDIT = '010102',
//   USERS_EXPORT = '010103',
//   ROLES_READ = '010200',
//   ROLES_CREATE = '010201',
//   ROLES_EDIT = '010202',
//   ROLES_EXPORT = '010203',
//   COMPANIES_READ = '010300',
//   COMPANIES_CREATE = '010301',
//   COMPANIES_EDIT = '010302',
//   COMPANIES_EXPORT = '010303',
//   UOM_READ = '020400',
//   UOM_CREATE = '020401',
//   UOM_EDIT = '020402',
//   UOM_EXPORT = '020403',
//   BRANDS_READ = '020500',
//   BRANDS_CREATE = '020501',
//   BRANDS_EDIT = '020502',
//   BRANDS_EXPORT = '020503',
//   INVTYPES_READ = '020600',
//   INVTYPES_CREATE = '020601',
//   INVTYPES_EDIT = '020602',
//   INVTYPES_EXPORT = '020603',
//   ENSMEMBERS_READ = '110100',
//   ENSMEMBERS_CREATE = '110101',
//   ENSMEMBERS_EDIT = '110102',
//   ENSMEMBERS_EXPORT = '110103',
//   ENSTEAMS_READ = '110200',
//   ENSTEAMS_CREATE = '110201',
//   ENSTEAMS_EDIT = '110202',
//   ENSTEAMS_EXPORT = '110203',
//   ENSSERVICIOS_READ = '110300',
//   ENSSERVICIOS_CREATE = '110301',
//   ENSSERVICIOS_EDIT = '110302',
//   ENSSERVICIOS_EXPORT = '110303',
//   ENSBOOKS_READ = '110400',
//   ENSBOOKS_CREATE = '110401',
//   ENSBOOKS_EDIT = '110402',
//   ENSBOOKS_EXPORT = '110403',
//   BITACORA_PLACES_READ = '120100',
//   BITACORA_PLACES_CREATE = '120101',
//   BITACORA_PLACES_EDIT = '120102',
//   BITACORA_PLACES_EXPORT = '120103',
//   BITACORA_CARS_READ = '120200',
//   BITACORA_CARS_CREATE = '120201',
//   BITACORA_CARS_EDIT = '120202',
//   BITACORA_CARS_EXPORT = '120203',
//   BITACORA_REASONS_READ = '120300',
//   BITACORA_REASONS_CREATE = '120301',
//   BITACORA_REASONS_EDIT = '120302',
//   BITACORA_REASONS_EXPORT = '120303',
//   BITACORA_EVENTS_READ = '120400',
//   BITACORA_EVENTS_CREATE = '120401',
//   BITACORA_EVENTS_EDIT = '120402',
//   BITACORA_EVENTS_EXPORT = '120403',
//   BITACORA_VISITS_READ = '120500',
//   BITACORA_VISITS_CREATE = '120501',
//   BITACORA_VISITS_EDIT = '120502',
//   BITACORA_VISITS_EXPORT = '120503',
//   BITACORA_RIDES_REASONS_READ = '120600',
//   BITACORA_RIDES_REASONS_CREATE = '120601',
//   BITACORA_RIDES_REASONS_EDIT = '120602',
//   BITACORA_RIDES_REASONS_EXPORT = '120603',
//   BITACORA_RIDES_READ = '120700',
//   BITACORA_RIDES_CREATE = '120701',
//   BITACORA_RIDES_EDIT = '120702',
//   BITACORA_RIDES_EXPORT = '120703',
//   BITACORA_REPORTS_VISITS = '129600',
//   BITACORA_REPORTS_EVENTS = '129700',
//   BITACORA_REPORTS_RIDES = '129800',
//   BITACORA_REPORTS_DASHBOARD = '129900',
// }